### ISSUE TITLE
test/data/*.json

### ISSUE THREAD

**Issue by waflessnet** [Daia-Systems-SPA/sii-dte-py#8]
hola, que tal como estan ? 
gracias por compartir! levante el servicio en un postgresql, pero no logro generar el archivo test/data/*.json para generar pdf, tienen un ejemplo para revisar ? 

saludos!

**Comment by waflessnet** [comment]
encontrado 
Saludos.

**Comment by MatthAmoros** [comment]
Hola @waflessnet,

Espero puedes utilizar nuestro proyecto, te cuento que en los proximos meses levantaremos una API publica gratis con la cual podrás generar tus DTE. Publicaremos un aviso en cuanto estará disponible.
